auth:
  strategy: token

deployment:
  replicas: 1
  namespace: istio-system

external_services:
  prometheus:
    external_url: http://prometheus-operated.monitoring.svc:9090
  grafana:
    external_url: http://grafana.monitoring.svc:3000
  tracing:
    external_url: http://jaeger-query.observability.svc:16686

istio_component_namespaces:
  istio_namespace: istio-system

server:
  port: 20001
